//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KamiYomu.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class I18n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal I18n() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KamiYomu.Web.Resources.I18n", typeof(I18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Accepted Formats.
        /// </summary>
        public static string AcceptedFormats {
            get {
                return ResourceManager.GetString("AcceptedFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept User Terms.
        /// </summary>
        public static string AcceptUserTerms {
            get {
                return ResourceManager.GetString("AcceptUserTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Crawler Agent To Get Started.
        /// </summary>
        public static string AddCrawlerAgentToGetStarted {
            get {
                return ResourceManager.GetString("AddCrawlerAgentToGetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add KamiYomu BaGet as Source.
        /// </summary>
        public static string AddKamiYomuBaGetAsSource {
            get {
                return ResourceManager.GetString("AddKamiYomuBaGetAsSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Nuget.org As Source.
        /// </summary>
        public static string AddNugetOrgAsSource {
            get {
                return ResourceManager.GetString("AddNugetOrgAsSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add NuGet Sources.
        /// </summary>
        public static string AddNuGetSources {
            get {
                return ResourceManager.GetString("AddNuGetSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-on Disclaimer.
        /// </summary>
        public static string AddonDisclaimer {
            get {
                return ResourceManager.GetString("AddonDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-on Explorer.
        /// </summary>
        public static string AddonExplorer {
            get {
                return ResourceManager.GetString("AddonExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-ons.
        /// </summary>
        public static string Addons {
            get {
                return ResourceManager.GetString("Addons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Library.
        /// </summary>
        public static string AddToLibrary {
            get {
                return ResourceManager.GetString("AddToLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Your Collection.
        /// </summary>
        public static string AddToYourCollection {
            get {
                return ResourceManager.GetString("AddToYourCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust the search term to explore available packages..
        /// </summary>
        public static string AdjustSearchTerm {
            get {
                return ResourceManager.GetString("AdjustSearchTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Actions.
        /// </summary>
        public static string AgentActions {
            get {
                return ResourceManager.GetString("AgentActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All chapter and volume download processes will be terminated..
        /// </summary>
        public static string AllchapterWillBeTerminated {
            get {
                return ResourceManager.GetString("AllchapterWillBeTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key.
        /// </summary>
        public static string APIKey {
            get {
                return ResourceManager.GetString("APIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Key or Password is required..
        /// </summary>
        public static string ApiKeyOrPasswordIsRequired {
            get {
                return ResourceManager.GetString("ApiKeyOrPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architecture.
        /// </summary>
        public static string Architecture {
            get {
                return ResourceManager.GetString("Architecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you certain you want to permanently delete this record?.
        /// </summary>
        public static string AreYouCertainYouWantPermanentlyDeleteThisRecord {
            get {
                return ResourceManager.GetString("AreYouCertainYouWantPermanentlyDeleteThisRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Properties.
        /// </summary>
        public static string AssemblyProperties {
            get {
                return ResourceManager.GetString("AssemblyProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt.
        /// </summary>
        public static string Attempt {
            get {
                return ResourceManager.GetString("Attempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        public static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Template Variables.
        /// </summary>
        public static string AvailableTemplateVariables {
            get {
                return ResourceManager.GetString("AvailableTemplateVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Jobs.
        /// </summary>
        public static string BackgroundJobs {
            get {
                return ResourceManager.GetString("BackgroundJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KamiYomu BaGet Feed.
        /// </summary>
        public static string BaGetFeed {
            get {
                return ResourceManager.GetString("BaGetFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBZ file size is below the expected threshold, indicating a failed download. Retrying shortly..
        /// </summary>
        public static string CbzIsTooSmall {
            get {
                return ResourceManager.GetString("CbzIsTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter.
        /// </summary>
        public static string Chapter {
            get {
                return ResourceManager.GetString("Chapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter Downloaded.
        /// </summary>
        public static string ChapterDownloaded {
            get {
                return ResourceManager.GetString("ChapterDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romance Sideways.
        /// </summary>
        public static string ChapterFunnyTemplate1 {
            get {
                return ResourceManager.GetString("ChapterFunnyTemplate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romance Slightly Tilted.
        /// </summary>
        public static string ChapterFunnyTemplate2 {
            get {
                return ResourceManager.GetString("ChapterFunnyTemplate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romance But Make It Weird.
        /// </summary>
        public static string ChapterFunnyTemplate3 {
            get {
                return ResourceManager.GetString("ChapterFunnyTemplate3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romance, Please Restart Me.
        /// </summary>
        public static string ChapterFunnyTemplate4 {
            get {
                return ResourceManager.GetString("ChapterFunnyTemplate4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapters.
        /// </summary>
        public static string Chapters {
            get {
                return ResourceManager.GetString("Chapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter Search Status.
        /// </summary>
        public static string ChapterSearchStatus {
            get {
                return ResourceManager.GetString("ChapterSearchStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapters Found.
        /// </summary>
        public static string ChaptersFound {
            get {
                return ResourceManager.GetString("ChaptersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection.
        /// </summary>
        public static string Collection {
            get {
                return ResourceManager.GetString("Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collections.
        /// </summary>
        public static string Collections {
            get {
                return ResourceManager.GetString("Collections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        public static string Community {
            get {
                return ResourceManager.GetString("Community", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatible.
        /// </summary>
        public static string Compatible {
            get {
                return ResourceManager.GetString("Compatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Add NuGet.org as Source.
        /// </summary>
        public static string ConfirmAddNugetOrg {
            get {
                return ResourceManager.GetString("ConfirmAddNugetOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NuGet.org is a public package repository not maintained by KamiYomu. Any developer can publish packages there, including experimental or potentially unsafe ones. Please review each package carefully before installing it into KamiYomu to ensure it meets your security, licensing, and stability requirements..
        /// </summary>
        public static string ConfirmAddNugetOrgSourceExplanation {
            get {
                return ResourceManager.GetString("ConfirmAddNugetOrgSourceExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection successfully!.
        /// </summary>
        public static string ConnectionSuccessfully {
            get {
                return ResourceManager.GetString("ConnectionSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Rating.
        /// </summary>
        public static string ContentRating {
            get {
                return ResourceManager.GetString("ContentRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawler.
        /// </summary>
        public static string Crawler {
            get {
                return ResourceManager.GetString("Crawler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawler Actions.
        /// </summary>
        public static string CrawlerActions {
            get {
                return ResourceManager.GetString("CrawlerActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawler Agent.
        /// </summary>
        public static string CrawlerAgent {
            get {
                return ResourceManager.GetString("CrawlerAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawler Agent Details.
        /// </summary>
        public static string CrawlerAgentDetails {
            get {
                return ResourceManager.GetString("CrawlerAgentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawler Agent Removed Successfully.
        /// </summary>
        public static string CrawlerAgentRemovedSuccessfully {
            get {
                return ResourceManager.GetString("CrawlerAgentRemovedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawler Agents.
        /// </summary>
        public static string CrawlerAgents {
            get {
                return ResourceManager.GetString("CrawlerAgents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawler Agent Saved Successfully!.
        /// </summary>
        public static string CrawlerAgentSavedSuccessfully {
            get {
                return ResourceManager.GetString("CrawlerAgentSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawler Settings.
        /// </summary>
        public static string CrawlerSettings {
            get {
                return ResourceManager.GetString("CrawlerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawl Manga.
        /// </summary>
        public static string CrawlManga {
            get {
                return ResourceManager.GetString("CrawlManga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically fetch chapters from supported manga sites and store them locally..
        /// </summary>
        public static string CrawlMangaDescription {
            get {
                return ResourceManager.GetString("CrawlMangaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Directory.
        /// </summary>
        public static string CurrentDirectory {
            get {
                return ResourceManager.GetString("CurrentDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Integration.
        /// </summary>
        public static string DeleteIntegration {
            get {
                return ResourceManager.GetString("DeleteIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispatch failed. The task will be rescheduled.
        /// </summary>
        public static string DispatchFailedMessage {
            get {
                return ResourceManager.GetString("DispatchFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Activity.
        /// </summary>
        public static string DownloadActivity {
            get {
                return ResourceManager.GetString("DownloadActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Chapter Has Been Cancelled.
        /// </summary>
        public static string DownloadChapterHasBeenCancelled {
            get {
                return ResourceManager.GetString("DownloadChapterHasBeenCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Chapter Has Been Scheduled.
        /// </summary>
        public static string DownloadChapterSchedule {
            get {
                return ResourceManager.GetString("DownloadChapterSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded.
        /// </summary>
        public static string Downloaded {
            get {
                return ResourceManager.GetString("Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Manga Has Been Cancelled.
        /// </summary>
        public static string DownloadMangaHasBeenCancelled {
            get {
                return ResourceManager.GetString("DownloadMangaHasBeenCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Progress.
        /// </summary>
        public static string DownloadProgress {
            get {
                return ResourceManager.GetString("DownloadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Status.
        /// </summary>
        public static string DownloadStatus {
            get {
                return ResourceManager.GetString("DownloadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Crawler Agent.
        /// </summary>
        public static string EditCrawlerAgent {
            get {
                return ResourceManager.GetString("EditCrawlerAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoy.
        /// </summary>
        public static string Enjoy {
            get {
                return ResourceManager.GetString("Enjoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples.
        /// </summary>
        public static string Examples {
            get {
                return ResourceManager.GetString("Examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Links.
        /// </summary>
        public static string ExternalLinks {
            get {
                return ResourceManager.GetString("ExternalLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Readers.
        /// </summary>
        public static string ExternalReaders {
            get {
                return ResourceManager.GetString("ExternalReaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to Kavita..
        /// </summary>
        public static string FailedConnectKavita {
            get {
                return ResourceManager.GetString("FailedConnectKavita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to search packages from the source..
        /// </summary>
        public static string FailedToSearch {
            get {
                return ResourceManager.GetString("FailedToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Safe Mode.
        /// </summary>
        public static string FamilySafeMode {
            get {
                return ResourceManager.GetString("FamilySafeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Safe Mode Disabled.
        /// </summary>
        public static string FamilySafeModeDisabled {
            get {
                return ResourceManager.GetString("FamilySafeModeDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Family Safe Mode is disabled. Content that may include mature or sensitive material will be shown..
        /// </summary>
        public static string FamilySafeModeDisableMessage {
            get {
                return ResourceManager.GetString("FamilySafeModeDisableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Safe Mode Enabled.
        /// </summary>
        public static string FamilySafeModeEnabled {
            get {
                return ResourceManager.GetString("FamilySafeModeEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Family Safe Mode is enabled. Content flagged as explicit or adult-oriented will be hidden..
        /// </summary>
        public static string FamilySafeModeEnableMessage {
            get {
                return ResourceManager.GetString("FamilySafeModeEnableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path.
        /// </summary>
        public static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path Format.
        /// </summary>
        public static string FilePathFormat {
            get {
                return ResourceManager.GetString("FilePathFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This template defines how your series will be saved. Each / represents a folder, so avoid starting or ending the file path with a slash. You can also use template variables to customize the path..
        /// </summary>
        public static string FilePathFormatDetails {
            get {
                return ResourceManager.GetString("FilePathFormatDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Version.
        /// </summary>
        public static string FileVersion {
            get {
                return ResourceManager.GetString("FileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Name.
        /// </summary>
        public static string FolderName {
            get {
                return ResourceManager.GetString("FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow.
        /// </summary>
        public static string Follow {
            get {
                return ResourceManager.GetString("Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following.
        /// </summary>
        public static string Following {
            get {
                return ResourceManager.GetString("Following", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framework Version.
        /// </summary>
        public static string FrameworkVersion {
            get {
                return ResourceManager.GetString("FrameworkVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From KamiYomu NuGet Repository - requires api key.
        /// </summary>
        public static string FromKamiYomuNuGetRepository {
            get {
                return ResourceManager.GetString("FromKamiYomuNuGetRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Scan Status.
        /// </summary>
        public static string FullScanStatus {
            get {
                return ResourceManager.GetString("FullScanStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open your Gotify instance in a browser..
        /// </summary>
        public static string GotifyTutorialApiKey01 {
            get {
                return ResourceManager.GetString("GotifyTutorialApiKey01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the Applications section..
        /// </summary>
        public static string GotifyTutorialApiKey02 {
            get {
                return ResourceManager.GetString("GotifyTutorialApiKey02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new application and name it KamiYomu..
        /// </summary>
        public static string GotifyTutorialApiKey03 {
            get {
                return ResourceManager.GetString("GotifyTutorialApiKey03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the generated token and paste it into the input above..
        /// </summary>
        public static string GotifyTutorialApiKey04 {
            get {
                return ResourceManager.GetString("GotifyTutorialApiKey04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got it.
        /// </summary>
        public static string GotIt {
            get {
                return ResourceManager.GetString("GotIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to add-on.
        /// </summary>
        public static string GoToAddOn {
            get {
                return ResourceManager.GetString("GoToAddOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Terms Accepted?.
        /// </summary>
        public static string HasTermsAccepted {
            get {
                return ResourceManager.GetString("HasTermsAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to get your Gotify token:.
        /// </summary>
        public static string HowToGetYourGotifyToken {
            get {
                return ResourceManager.GetString("HowToGetYourGotifyToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Crawler Agent .
        /// </summary>
        public static string ImportCrawlerAgent {
            get {
                return ResourceManager.GetString("ImportCrawlerAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Pre-Release Versions.
        /// </summary>
        public static string IncludePreReleaseVersions {
            get {
                return ResourceManager.GetString("IncludePreReleaseVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-release versions include alpha, beta, and release candidate builds that may contain new features but are not yet considered stable. Use with caution..
        /// </summary>
        public static string IncludePreReleaseVersionsExplanation {
            get {
                return ResourceManager.GetString("IncludePreReleaseVersionsExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informational Version.
        /// </summary>
        public static string InformationalVersion {
            get {
                return ResourceManager.GetString("InformationalVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install a Crawler Agent.
        /// </summary>
        public static string InstallACrawlerAgent {
            get {
                return ResourceManager.GetString("InstallACrawlerAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhance KamiYomu by installing crawler agents that automatically track and retrieve your manga as soon as it becomes available..
        /// </summary>
        public static string InstallCrawlerAgentDescription {
            get {
                return ResourceManager.GetString("InstallCrawlerAgentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrations.
        /// </summary>
        public static string Integrations {
            get {
                return ResourceManager.GetString("Integrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kavita Integration Settings.
        /// </summary>
        public static string KavitaIntegrationSettings {
            get {
                return ResourceManager.GetString("KavitaIntegrationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access your Kavita instance.
        /// </summary>
        public static string KavitaTutorialApiKey01 {
            get {
                return ResourceManager.GetString("KavitaTutorialApiKey01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in in your account.
        /// </summary>
        public static string KavitaTutorialApiKey02 {
            get {
                return ResourceManager.GetString("KavitaTutorialApiKey02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access the configuration &gt; API Key / OPDS.
        /// </summary>
        public static string KavitaTutorialApiKey03 {
            get {
                return ResourceManager.GetString("KavitaTutorialApiKey03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the generated token and paste it into the input above.
        /// </summary>
        public static string KavitaTutorialApiKey04 {
            get {
                return ResourceManager.GetString("KavitaTutorialApiKey04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Update.
        /// </summary>
        public static string LastUpdate {
            get {
                return ResourceManager.GetString("LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Volume.
        /// </summary>
        public static string LastVolume {
            get {
                return ResourceManager.GetString("LastVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Chapter.
        /// </summary>
        public static string LatestChapter {
            get {
                return ResourceManager.GetString("LatestChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Not Found.
        /// </summary>
        public static string LibraryNotFound {
            get {
                return ResourceManager.GetString("LibraryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging out....
        /// </summary>
        public static string LoggingOut {
            get {
                return ResourceManager.GetString("LoggingOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Stream.
        /// </summary>
        public static string LogStream {
            get {
                return ResourceManager.GetString("LogStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Name.
        /// </summary>
        public static string MachineName {
            get {
                return ResourceManager.GetString("MachineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make this the default setting for future collections..
        /// </summary>
        public static string MakeThisTheDefaultSettingForFutureCollections {
            get {
                return ResourceManager.GetString("MakeThisTheDefaultSettingForFutureCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mangá.
        /// </summary>
        public static string Manga {
            get {
                return ResourceManager.GetString("Manga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manga Crawler Platform.
        /// </summary>
        public static string MangaCrawlerPlatform {
            get {
                return ResourceManager.GetString("MangaCrawlerPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mangás.
        /// </summary>
        public static string Mangas {
            get {
                return ResourceManager.GetString("Mangas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access unofficial or third-party sources to retrieve manga content.
        /// </summary>
        public static string ModalAccessUnofficialThirdPartySourcesManga {
            get {
                return ResourceManager.GetString("ModalAccessUnofficialThirdPartySourcesManga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t show this message again.
        /// </summary>
        public static string ModalDontShowThisMessageAgain {
            get {
                return ResourceManager.GetString("ModalDontShowThisMessageAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include code or behavior not reviewed or endorsed by the KamiYomu team.
        /// </summary>
        public static string ModalIncludeCodeBehaviorNotEndorsedKamiYomu {
            get {
                return ResourceManager.GetString("ModalIncludeCodeBehaviorNotEndorsedKamiYomu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KamiYomu does not provide support for community add-ons and assumes no responsibility for their functionality, safety, or legality..
        /// </summary>
        public static string ModalKamiYomuNotProvideSupportCommunityAddons {
            get {
                return ResourceManager.GetString("ModalKamiYomuNotProvideSupportCommunityAddons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pose potential security or privacy risks if not properly vetted.
        /// </summary>
        public static string ModalPosePotentialSecurityPrivacyRisks {
            get {
                return ResourceManager.GetString("ModalPosePotentialSecurityPrivacyRisks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before installing any add-on: review the source code in its public repository, verify that it is open source, and avoid installing if the source is unavailable or untrusted..
        /// </summary>
        public static string ModalReviewAddonRepositoryBeforeInstall {
            get {
                return ResourceManager.GetString("ModalReviewAddonRepositoryBeforeInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some add-ons available through this platform are developed and maintained by the community. These community add-ons may:.
        /// </summary>
        public static string ModalSomeAddonsAvailableMaintainedCommunity {
            get {
                return ResourceManager.GetString("ModalSomeAddonsAvailableMaintainedCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyGet feed.
        /// </summary>
        public static string MyGetFeed {
            get {
                return ResourceManager.GetString("MyGetFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Add-ons Available.
        /// </summary>
        public static string NoAddonsAvailable {
            get {
                return ResourceManager.GetString("NoAddonsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Crawler Agent.
        /// </summary>
        public static string NoCrawlerAgent {
            get {
                return ResourceManager.GetString("NoCrawlerAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No .dll found in NuGet package..
        /// </summary>
        public static string NoDllFoundInNugetPackage {
            get {
                return ResourceManager.GetString("NoDllFoundInNugetPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file was found..
        /// </summary>
        public static string NoFileWasFound {
            get {
                return ResourceManager.GetString("NoFileWasFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Sources.
        /// </summary>
        public static string NoSources {
            get {
                return ResourceManager.GetString("NoSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Compatible.
        /// </summary>
        public static string NotCompatible {
            get {
                return ResourceManager.GetString("NotCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Providers.
        /// </summary>
        public static string NotificationProviders {
            get {
                return ResourceManager.GetString("NotificationProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Safe For Work.
        /// </summary>
        public static string NotSafeForWork {
            get {
                return ResourceManager.GetString("NotSafeForWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Started.
        /// </summary>
        public static string NotStarted {
            get {
                return ResourceManager.GetString("NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Stated.
        /// </summary>
        public static string NotStated {
            get {
                return ResourceManager.GetString("NotStated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuget.org has been added as a NuGet Source.
        /// </summary>
        public static string NugetOrgHasBeenAddedAsANugetSource {
            get {
                return ResourceManager.GetString("NugetOrgHasBeenAddedAsANugetSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NuGet Package Installed Successfully.
        /// </summary>
        public static string NuGetPackageInstalledSuccessfully {
            get {
                return ResourceManager.GetString("NuGetPackageInstalledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NuGet Package is Invalid.
        /// </summary>
        public static string NuGetPackageIsInvalid {
            get {
                return ResourceManager.GetString("NuGetPackageIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required for authenticated sources. Enter either the password for basic auth or an API key for token-based access. This will be used to fetch packages securely..
        /// </summary>
        public static string NugetSourcePasswordExplanation {
            get {
                return ResourceManager.GetString("NugetSourcePasswordExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional. Provide a username if the NuGet source requires basic authentication. Leave blank for public feeds or API key-only access..
        /// </summary>
        public static string NugetSourceUserNameExplanation {
            get {
                return ResourceManager.GetString("NugetSourceUserNameExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to official NuGet.org.
        /// </summary>
        public static string OfficialNuGetOrg {
            get {
                return ResourceManager.GetString("OfficialNuGetOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only .dll or .nupkg files are supported..
        /// </summary>
        public static string OnlyDllOrNupkgSupported {
            get {
                return ResourceManager.GetString("OnlyDllOrNupkgSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Library.
        /// </summary>
        public static string OpenLibrary {
            get {
                return ResourceManager.GetString("OpenLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Your Collection.
        /// </summary>
        public static string OpenYourCollection {
            get {
                return ResourceManager.GetString("OpenYourCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operational System Version.
        /// </summary>
        public static string OperationalSystemVersion {
            get {
                return ResourceManager.GetString("OperationalSystemVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Language.
        /// </summary>
        public static string OriginalLanguage {
            get {
                return ResourceManager.GetString("OriginalLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look for new titles across your selected sources..
        /// </summary>
        public static string PageSubtitleCrawler {
            get {
                return ResourceManager.GetString("PageSubtitleCrawler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your manga collection - including titles currently downloading and those already completed..
        /// </summary>
        public static string PageSubtitleLibrary {
            get {
                return ResourceManager.GetString("PageSubtitleLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password / API Key.
        /// </summary>
        public static string PasswordApiKey {
            get {
                return ResourceManager.GetString("PasswordApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste your Gotify app token here..
        /// </summary>
        public static string PasteYourGotifyAppTokenHere {
            get {
                return ResourceManager.GetString("PasteYourGotifyAppTokenHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct the highlighted field..
        /// </summary>
        public static string PleaseCorrectHighlightedField {
            get {
                return ResourceManager.GetString("PleaseCorrectHighlightedField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fix the following errors.
        /// </summary>
        public static string PleaseFixFollowingErrors {
            get {
                return ResourceManager.GetString("PleaseFixFollowingErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fix validation errors.
        /// </summary>
        public static string PleaseFixValidationErrors {
            get {
                return ResourceManager.GetString("PleaseFixValidationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview will appear here.
        /// </summary>
        public static string PreviewWillAppearHere {
            get {
                return ResourceManager.GetString("PreviewWillAppearHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing... Certain crawler agents require more time depending on the complexity of the task..
        /// </summary>
        public static string ProcessingCertainCrawlerAgentaRequireMoreTime {
            get {
                return ResourceManager.GetString("ProcessingCertainCrawlerAgentaRequireMoreTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor Count.
        /// </summary>
        public static string ProcessorCount {
            get {
                return ResourceManager.GetString("ProcessorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of logical processors available. This value is often used as a baseline
        ///for Hangfire&apos;s &lt;code&gt;WorkerCount&lt;/code&gt; setting to control how many jobs can run concurrently..
        /// </summary>
        public static string ProcessorCountExplanation {
            get {
                return ResourceManager.GetString("ProcessorCountExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read It Online.
        /// </summary>
        public static string ReadItOnline {
            get {
                return ResourceManager.GetString("ReadItOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Status.
        /// </summary>
        public static string ReleaseStatus {
            get {
                return ResourceManager.GetString("ReleaseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove From Library.
        /// </summary>
        public static string RemoveFromLibrary {
            get {
                return ResourceManager.GetString("RemoveFromLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove From Your Collection.
        /// </summary>
        public static string RemoveFromYourCollection {
            get {
                return ResourceManager.GetString("RemoveFromYourCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reschedule.
        /// </summary>
        public static string Reschedule {
            get {
                return ResourceManager.GetString("Reschedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled.
        /// </summary>
        public static string Scheduled {
            get {
                return ResourceManager.GetString("Scheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Crawler Agents.
        /// </summary>
        public static string SearchCrawlerAgents {
            get {
                return ResourceManager.GetString("SearchCrawlerAgents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search For Chapters.
        /// </summary>
        public static string SearchForChapters {
            get {
                return ResourceManager.GetString("SearchForChapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for chapters is completed.
        /// </summary>
        public static string SearchForChaptersCompleted {
            get {
                return ResourceManager.GetString("SearchForChaptersCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search manga....
        /// </summary>
        public static string SearchManga {
            get {
                return ResourceManager.GetString("SearchManga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See the documentation..
        /// </summary>
        public static string SeeTheDocumentation {
            get {
                return ResourceManager.GetString("SeeTheDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See the license.
        /// </summary>
        public static string SeeTheLicense {
            get {
                return ResourceManager.GetString("SeeTheLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Your Collection.
        /// </summary>
        public static string SeeYourCollection {
            get {
                return ResourceManager.GetString("SeeYourCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Crawler Agent.
        /// </summary>
        public static string SelectCrawlerAgent {
            get {
                return ResourceManager.GetString("SelectCrawlerAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Source.
        /// </summary>
        public static string SelectSource {
            get {
                return ResourceManager.GetString("SelectSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series.
        /// </summary>
        public static string Series {
            get {
                return ResourceManager.GetString("Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is used by reader programs to organize chapters into series. It helps the programs identify which series a chapter belongs to, making navigation and management easier for the user..
        /// </summary>
        public static string SeriesFormatDetails {
            get {
                return ResourceManager.GetString("SeriesFormatDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series Name Format.
        /// </summary>
        public static string SeriesNameFormat {
            get {
                return ResourceManager.GetString("SeriesNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Uri.
        /// </summary>
        public static string ServiceUri {
            get {
                return ResourceManager.GetString("ServiceUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Uri Invalid.
        /// </summary>
        public static string ServiceUriInvalid {
            get {
                return ResourceManager.GetString("ServiceUriInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Uri Required.
        /// </summary>
        public static string ServiceUriRequired {
            get {
                return ResourceManager.GetString("ServiceUriRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Removed Successfully!.
        /// </summary>
        public static string SettingsRemovedSuccessfully {
            get {
                return ResourceManager.GetString("SettingsRemovedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved successfully!.
        /// </summary>
        public static string SettingsSavedSuccessfully {
            get {
                return ResourceManager.GetString("SettingsSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Up Your Download.
        /// </summary>
        public static string SetUpYourDownload {
            get {
                return ResourceManager.GetString("SetUpYourDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this section to customize how downloaded files are saved, including the file path and comic information. You can use template variables (defined below) that automatically update based on manga and chapter details. Example data for these variables is available in the template variable section..
        /// </summary>
        public static string SetUpYourDownloadDetails {
            get {
                return ResourceManager.GetString("SetUpYourDownloadDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Media.
        /// </summary>
        public static string SocialMedia {
            get {
                return ResourceManager.GetString("SocialMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something Went Wrong..
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Code.
        /// </summary>
        public static string SourceCode {
            get {
                return ResourceManager.GetString("SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source removed successfully.
        /// </summary>
        public static string SourceRemovedSuccessfully {
            get {
                return ResourceManager.GetString("SourceRemovedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources.
        /// </summary>
        public static string Sources {
            get {
                return ResourceManager.GetString("Sources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard default settings are shown below. You can modify these using environment variables..
        /// </summary>
        public static string StandardDefaultSettingsAreShownBelowExplain {
            get {
                return ResourceManager.GetString("StandardDefaultSettingsAreShownBelowExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Crawling Now.
        /// </summary>
        public static string StartCrawlingNow {
            get {
                return ResourceManager.GetString("StartCrawlingNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Download Your Manga.
        /// </summary>
        public static string StartDownloadYourManga {
            get {
                return ResourceManager.GetString("StartDownloadYourManga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Information.
        /// </summary>
        public static string SystemInformation {
            get {
                return ResourceManager.GetString("SystemInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Connection.
        /// </summary>
        public static string TestConnection {
            get {
                return ResourceManager.GetString("TestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TheConnectionHasFailed.
        /// </summary>
        public static string TheConnectionHasFailed {
            get {
                return ResourceManager.GetString("TheConnectionHasFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template must produce unique file names for different chapters..
        /// </summary>
        public static string TheTemplateMustProduceUniqueFileNames {
            get {
                return ResourceManager.GetString("TheTemplateMustProduceUniqueFileNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like the template is missing or invalid. Please enter a valid one..
        /// </summary>
        public static string TheTemplatePathIsMissingOrInvalid {
            get {
                return ResourceManager.GetString("TheTemplatePathIsMissingOrInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Value Is Required.
        /// </summary>
        public static string ThisValueIsRequired {
            get {
                return ResourceManager.GetString("ThisValueIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A timeout is the maximum amount of time a client will wait for an operation to finish before giving up. (in milliseconds).
        /// </summary>
        public static string TimeoutExplanation {
            get {
                return ResourceManager.GetString("TimeoutExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title added to your collection.
        /// </summary>
        public static string TitleAddedToYourCollection {
            get {
                return ResourceManager.GetString("TitleAddedToYourCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Format.
        /// </summary>
        public static string TitleFormat {
            get {
                return ResourceManager.GetString("TitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is used by reader programs to organize chapter order. It helps the program determine the correct sequence of chapters in a series or manga, making navigation and management easier for the user..
        /// </summary>
        public static string TitleFormatDetails {
            get {
                return ResourceManager.GetString("TitleFormatDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Be Rescheduled.
        /// </summary>
        public static string ToBeRescheduled {
            get {
                return ResourceManager.GetString("ToBeRescheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Theme.
        /// </summary>
        public static string ToggleTheme {
            get {
                return ResourceManager.GetString("ToggleTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Downloads.
        /// </summary>
        public static string TotalDownloads {
            get {
                return ResourceManager.GetString("TotalDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A User-Agent is a text string that a web browser or HTTP client sends along with its requests to a server..
        /// </summary>
        public static string UserAgentExplanation {
            get {
                return ResourceManager.GetString("UserAgentExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Interface Language Has Been Changed.
        /// </summary>
        public static string UserInterfaceLanguageChanged {
            get {
                return ResourceManager.GetString("UserInterfaceLanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username Required.
        /// </summary>
        public static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Terms.
        /// </summary>
        public static string UserTerms {
            get {
                return ResourceManager.GetString("UserTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must accept the terms before saving this agent..
        /// </summary>
        public static string ValidateMessageYouMustAcceptTermsBeforeAgent {
            get {
                return ResourceManager.GetString("ValidateMessageYouMustAcceptTermsBeforeAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Library.
        /// </summary>
        public static string ViewLibrary {
            get {
                return ResourceManager.GetString("ViewLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse your downloaded manga collection through a clean, customizable interface..
        /// </summary>
        public static string ViewLibraryDescription {
            get {
                return ResourceManager.GetString("ViewLibraryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volumes.
        /// </summary>
        public static string Volumes {
            get {
                return ResourceManager.GetString("Volumes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are still processing, believe in us.
        /// </summary>
        public static string WaitProcessing1 {
            get {
                return ResourceManager.GetString("WaitProcessing1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can&apos;t wait until it is done.
        /// </summary>
        public static string WaitProcessing2 {
            get {
                return ResourceManager.GetString("WaitProcessing2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almost there... maybe.
        /// </summary>
        public static string WaitProcessing3 {
            get {
                return ResourceManager.GetString("WaitProcessing3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still spinning... like your favorite vinyl.
        /// </summary>
        public static string WaitProcessing4 {
            get {
                return ResourceManager.GetString("WaitProcessing4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This spinner is doing its best.
        /// </summary>
        public static string WaitProcessing5 {
            get {
                return ResourceManager.GetString("WaitProcessing5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome To.
        /// </summary>
        public static string WelcomeTo {
            get {
                return ResourceManager.GetString("WelcomeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to KamiYomu.
        /// </summary>
        public static string WelcomeToKamiYomu {
            get {
                return ResourceManager.GetString("WelcomeToKamiYomu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fully self-hosted manga crawler. No external servers, no tracking — your collection stays entirely under your control..
        /// </summary>
        public static string WelcomeToKamiYomuDescription {
            get {
                return ResourceManager.GetString("WelcomeToKamiYomuDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this manga from your collection? This action cannot be undone. .
        /// </summary>
        public static string YouAreAboutToDeleteThisMangaFromYourCollection {
            get {
                return ResourceManager.GetString("YouAreAboutToDeleteThisMangaFromYourCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You’ve stopped following this title. New chapters will no longer be checked automatically..
        /// </summary>
        public static string YouAreNoLongerFollowingThisTitle {
            get {
                return ResourceManager.GetString("YouAreNoLongerFollowingThisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Collection.
        /// </summary>
        public static string YourCollection {
            get {
                return ResourceManager.GetString("YourCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your collection no longer includes.
        /// </summary>
        public static string YourCollectionNoLongerIncludes {
            get {
                return ResourceManager.GetString("YourCollectionNoLongerIncludes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your manga will be stored using the following file path format:.
        /// </summary>
        public static string YourMangaWillBeStoredFilePathFormat {
            get {
                return ResourceManager.GetString("YourMangaWillBeStoredFilePathFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You’re now following this title. We’ll automatically check for new chapters..
        /// </summary>
        public static string YouStartedFollowingThisTitle {
            get {
                return ResourceManager.GetString("YouStartedFollowingThisTitle", resourceCulture);
            }
        }
    }
}
