//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KamiYomu.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class I18n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal I18n() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KamiYomu.Web.Resources.I18n", typeof(I18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Accepted Formats.
        /// </summary>
        internal static string AcceptedFormats {
            get {
                return ResourceManager.GetString("AcceptedFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept User Terms.
        /// </summary>
        internal static string AcceptUserTerms {
            get {
                return ResourceManager.GetString("AcceptUserTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Crawler Agent To Get Started.
        /// </summary>
        internal static string AddCrawlerAgentToGetStarted {
            get {
                return ResourceManager.GetString("AddCrawlerAgentToGetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add NuGet Sources.
        /// </summary>
        internal static string AddNuGetSources {
            get {
                return ResourceManager.GetString("AddNuGetSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-on Disclaimer.
        /// </summary>
        internal static string AddonDisclaimer {
            get {
                return ResourceManager.GetString("AddonDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-on Explorer.
        /// </summary>
        internal static string AddonExplorer {
            get {
                return ResourceManager.GetString("AddonExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-ons.
        /// </summary>
        internal static string Addons {
            get {
                return ResourceManager.GetString("Addons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Library.
        /// </summary>
        internal static string AddToLibrary {
            get {
                return ResourceManager.GetString("AddToLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Your Collection.
        /// </summary>
        internal static string AddToYourCollection {
            get {
                return ResourceManager.GetString("AddToYourCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Actions.
        /// </summary>
        internal static string AgentActions {
            get {
                return ResourceManager.GetString("AgentActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All chapter and volume download processes will be terminated..
        /// </summary>
        internal static string AllchapterWillBeTerminated {
            get {
                return ResourceManager.GetString("AllchapterWillBeTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key.
        /// </summary>
        internal static string APIKey {
            get {
                return ResourceManager.GetString("APIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Properties.
        /// </summary>
        internal static string AssemblyProperties {
            get {
                return ResourceManager.GetString("AssemblyProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        internal static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Jobs.
        /// </summary>
        internal static string BackgroundJobs {
            get {
                return ResourceManager.GetString("BackgroundJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter.
        /// </summary>
        internal static string Chapter {
            get {
                return ResourceManager.GetString("Chapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapters.
        /// </summary>
        internal static string Chapters {
            get {
                return ResourceManager.GetString("Chapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapters Found.
        /// </summary>
        internal static string ChaptersFound {
            get {
                return ResourceManager.GetString("ChaptersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection.
        /// </summary>
        internal static string Collection {
            get {
                return ResourceManager.GetString("Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collections.
        /// </summary>
        internal static string Collections {
            get {
                return ResourceManager.GetString("Collections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Rating.
        /// </summary>
        internal static string ContentRating {
            get {
                return ResourceManager.GetString("ContentRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawler.
        /// </summary>
        internal static string Crawler {
            get {
                return ResourceManager.GetString("Crawler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawler Actions.
        /// </summary>
        internal static string CrawlerActions {
            get {
                return ResourceManager.GetString("CrawlerActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawler Agent.
        /// </summary>
        internal static string CrawlerAgent {
            get {
                return ResourceManager.GetString("CrawlerAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawler Agent Details.
        /// </summary>
        internal static string CrawlerAgentDetails {
            get {
                return ResourceManager.GetString("CrawlerAgentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawler Agents.
        /// </summary>
        internal static string CrawlerAgents {
            get {
                return ResourceManager.GetString("CrawlerAgents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawler Agent Saved Successfully!.
        /// </summary>
        internal static string CrawlerAgentSavedSuccessfully {
            get {
                return ResourceManager.GetString("CrawlerAgentSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawler Settings.
        /// </summary>
        internal static string CrawlerSettings {
            get {
                return ResourceManager.GetString("CrawlerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawl Manga.
        /// </summary>
        internal static string CrawlManga {
            get {
                return ResourceManager.GetString("CrawlManga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically fetch chapters from supported manga sites and store them locally..
        /// </summary>
        internal static string CrawlMangaDescription {
            get {
                return ResourceManager.GetString("CrawlMangaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        internal static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded.
        /// </summary>
        internal static string Downloaded {
            get {
                return ResourceManager.GetString("Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Crawler Agent.
        /// </summary>
        internal static string EditCrawlerAgent {
            get {
                return ResourceManager.GetString("EditCrawlerAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoy.
        /// </summary>
        internal static string Enjoy {
            get {
                return ResourceManager.GetString("Enjoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples.
        /// </summary>
        internal static string Examples {
            get {
                return ResourceManager.GetString("Examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Links.
        /// </summary>
        internal static string ExternalLinks {
            get {
                return ResourceManager.GetString("ExternalLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Version.
        /// </summary>
        internal static string FileVersion {
            get {
                return ResourceManager.GetString("FileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Name.
        /// </summary>
        internal static string FolderName {
            get {
                return ResourceManager.GetString("FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From KamiYomu NuGet Repository - requires api key.
        /// </summary>
        internal static string FromKamiYomuNuGetRepository {
            get {
                return ResourceManager.GetString("FromKamiYomuNuGetRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got it.
        /// </summary>
        internal static string GotIt {
            get {
                return ResourceManager.GetString("GotIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to add-on.
        /// </summary>
        internal static string GoToAddOn {
            get {
                return ResourceManager.GetString("GoToAddOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Terms Accepted?.
        /// </summary>
        internal static string HasTermsAccepted {
            get {
                return ResourceManager.GetString("HasTermsAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Crawler Agent .
        /// </summary>
        internal static string ImportCrawlerAgent {
            get {
                return ResourceManager.GetString("ImportCrawlerAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informational Version.
        /// </summary>
        internal static string InformationalVersion {
            get {
                return ResourceManager.GetString("InformationalVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install a Crawler Agent.
        /// </summary>
        internal static string InstallACrawlerAgent {
            get {
                return ResourceManager.GetString("InstallACrawlerAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Volume.
        /// </summary>
        internal static string LastVolume {
            get {
                return ResourceManager.GetString("LastVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Chapter.
        /// </summary>
        internal static string LatestChapter {
            get {
                return ResourceManager.GetString("LatestChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        internal static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Stream.
        /// </summary>
        internal static string LogStream {
            get {
                return ResourceManager.GetString("LogStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mangá.
        /// </summary>
        internal static string Manga {
            get {
                return ResourceManager.GetString("Manga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manga Crawler Platform.
        /// </summary>
        internal static string MangaCrawlerPlatform {
            get {
                return ResourceManager.GetString("MangaCrawlerPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mangás.
        /// </summary>
        internal static string Mangas {
            get {
                return ResourceManager.GetString("Mangas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access unofficial or third-party sources to retrieve manga content.
        /// </summary>
        internal static string ModalAccessUnofficialThirdPartySourcesManga {
            get {
                return ResourceManager.GetString("ModalAccessUnofficialThirdPartySourcesManga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t show this message again.
        /// </summary>
        internal static string ModalDontShowThisMessageAgain {
            get {
                return ResourceManager.GetString("ModalDontShowThisMessageAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include code or behavior not reviewed or endorsed by the KamiYomu team.
        /// </summary>
        internal static string ModalIncludeCodeBehaviorNotEndorsedKamiYomu {
            get {
                return ResourceManager.GetString("ModalIncludeCodeBehaviorNotEndorsedKamiYomu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KamiYomu does not provide support for community add-ons and assumes no responsibility for their functionality, safety, or legality..
        /// </summary>
        internal static string ModalKamiYomuNotProvideSupportCommunityAddons {
            get {
                return ResourceManager.GetString("ModalKamiYomuNotProvideSupportCommunityAddons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pose potential security or privacy risks if not properly vetted.
        /// </summary>
        internal static string ModalPosePotentialSecurityPrivacyRisks {
            get {
                return ResourceManager.GetString("ModalPosePotentialSecurityPrivacyRisks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before installing any add-on: review the source code in its public repository, verify that it is open source, and avoid installing if the source is unavailable or untrusted..
        /// </summary>
        internal static string ModalReviewAddonRepositoryBeforeInstall {
            get {
                return ResourceManager.GetString("ModalReviewAddonRepositoryBeforeInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some add-ons available through this platform are developed and maintained by the community. These community add-ons may:.
        /// </summary>
        internal static string ModalSomeAddonsAvailableMaintainedCommunity {
            get {
                return ResourceManager.GetString("ModalSomeAddonsAvailableMaintainedCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyGet feed.
        /// </summary>
        internal static string MyGetFeed {
            get {
                return ResourceManager.GetString("MyGetFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Add-ons Available.
        /// </summary>
        internal static string NoAddonsAvailable {
            get {
                return ResourceManager.GetString("NoAddonsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Crawler Agent.
        /// </summary>
        internal static string NoCrawlerAgent {
            get {
                return ResourceManager.GetString("NoCrawlerAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Sources.
        /// </summary>
        internal static string NoSources {
            get {
                return ResourceManager.GetString("NoSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required for authenticated sources. Enter either the password for basic auth or an API key for token-based access. This will be used to fetch packages securely..
        /// </summary>
        internal static string NugetSourcePasswordExplanation {
            get {
                return ResourceManager.GetString("NugetSourcePasswordExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional. Provide a username if the NuGet source requires basic authentication. Leave blank for public feeds or API key-only access..
        /// </summary>
        internal static string NugetSourceUserNameExplanation {
            get {
                return ResourceManager.GetString("NugetSourceUserNameExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to official NuGet.org.
        /// </summary>
        internal static string OfficialNuGetOrg {
            get {
                return ResourceManager.GetString("OfficialNuGetOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Library.
        /// </summary>
        internal static string OpenLibrary {
            get {
                return ResourceManager.GetString("OpenLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Your Collection.
        /// </summary>
        internal static string OpenYourCollection {
            get {
                return ResourceManager.GetString("OpenYourCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Language.
        /// </summary>
        internal static string OriginalLanguage {
            get {
                return ResourceManager.GetString("OriginalLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look for new titles across your selected sources..
        /// </summary>
        internal static string PageSubtitleCrawler {
            get {
                return ResourceManager.GetString("PageSubtitleCrawler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your manga collection - including titles currently downloading and those already completed..
        /// </summary>
        internal static string PageSubtitleLibrary {
            get {
                return ResourceManager.GetString("PageSubtitleLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing... Certain crawler agents require more time depending on the complexity of the task..
        /// </summary>
        internal static string ProcessingCertainCrawlerAgentaRequireMoreTime {
            get {
                return ResourceManager.GetString("ProcessingCertainCrawlerAgentaRequireMoreTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Status.
        /// </summary>
        internal static string ReleaseStatus {
            get {
                return ResourceManager.GetString("ReleaseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove From Library.
        /// </summary>
        internal static string RemoveFromLibrary {
            get {
                return ResourceManager.GetString("RemoveFromLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove From Your Collection.
        /// </summary>
        internal static string RemoveFromYourCollection {
            get {
                return ResourceManager.GetString("RemoveFromYourCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Crawler Agents.
        /// </summary>
        internal static string SearchCrawlerAgents {
            get {
                return ResourceManager.GetString("SearchCrawlerAgents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search manga....
        /// </summary>
        internal static string SearchManga {
            get {
                return ResourceManager.GetString("SearchManga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See the license.
        /// </summary>
        internal static string SeeTheLicense {
            get {
                return ResourceManager.GetString("SeeTheLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Your Collection.
        /// </summary>
        internal static string SeeYourCollection {
            get {
                return ResourceManager.GetString("SeeYourCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Crawler Agent.
        /// </summary>
        internal static string SelectCrawlerAgent {
            get {
                return ResourceManager.GetString("SelectCrawlerAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Source.
        /// </summary>
        internal static string SelectSource {
            get {
                return ResourceManager.GetString("SelectSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Code.
        /// </summary>
        internal static string SourceCode {
            get {
                return ResourceManager.GetString("SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources.
        /// </summary>
        internal static string Sources {
            get {
                return ResourceManager.GetString("Sources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Crawling Now.
        /// </summary>
        internal static string StartCrawlingNow {
            get {
                return ResourceManager.GetString("StartCrawlingNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Download Your Mangas.
        /// </summary>
        internal static string StartDownloadYourMangas {
            get {
                return ResourceManager.GetString("StartDownloadYourMangas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Theme.
        /// </summary>
        internal static string ToggleTheme {
            get {
                return ResourceManager.GetString("ToggleTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Downloads.
        /// </summary>
        internal static string TotalDownloads {
            get {
                return ResourceManager.GetString("TotalDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Terms.
        /// </summary>
        internal static string UserTerms {
            get {
                return ResourceManager.GetString("UserTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must accept the terms before saving this agent..
        /// </summary>
        internal static string ValidateMessageYouMustAcceptTermsBeforeAgent {
            get {
                return ResourceManager.GetString("ValidateMessageYouMustAcceptTermsBeforeAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Library.
        /// </summary>
        internal static string ViewLibrary {
            get {
                return ResourceManager.GetString("ViewLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse your downloaded manga collection through a clean, customizable interface..
        /// </summary>
        internal static string ViewLibraryDescription {
            get {
                return ResourceManager.GetString("ViewLibraryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volumes.
        /// </summary>
        internal static string Volumes {
            get {
                return ResourceManager.GetString("Volumes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are still processing, believe in us.
        /// </summary>
        internal static string WaitProcessing1 {
            get {
                return ResourceManager.GetString("WaitProcessing1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can&apos;t wait until it is done.
        /// </summary>
        internal static string WaitProcessing2 {
            get {
                return ResourceManager.GetString("WaitProcessing2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almost there... maybe.
        /// </summary>
        internal static string WaitProcessing3 {
            get {
                return ResourceManager.GetString("WaitProcessing3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still spinning... like your favorite vinyl.
        /// </summary>
        internal static string WaitProcessing4 {
            get {
                return ResourceManager.GetString("WaitProcessing4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This spinner is doing its best.
        /// </summary>
        internal static string WaitProcessing5 {
            get {
                return ResourceManager.GetString("WaitProcessing5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to KamiYomu.
        /// </summary>
        internal static string WelcomeToKamiYomu {
            get {
                return ResourceManager.GetString("WelcomeToKamiYomu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fully self-hosted manga crawler. No external servers, no tracking — your collection stays entirely under your control..
        /// </summary>
        internal static string WelcomeToKamiYomuDescription {
            get {
                return ResourceManager.GetString("WelcomeToKamiYomuDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this manga from your collection? This action cannot be undone. .
        /// </summary>
        internal static string YouAreAboutToDeleteThisMangaFromYourCollection {
            get {
                return ResourceManager.GetString("YouAreAboutToDeleteThisMangaFromYourCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Collection.
        /// </summary>
        internal static string YourCollection {
            get {
                return ResourceManager.GetString("YourCollection", resourceCulture);
            }
        }
    }
}
